version: 2.1

executors:
  buildpack:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo

jobs:
  build-docker-image:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t scaleway-cli .
      - run:
          name: Check kubectl
          command: docker run -it scaleway-cli "which" "kubectl"
      - run:
          name: Check scaleway
          command: docker run -it scaleway-cli "scw" "--version"
      - run:
          name: Check all versions
          command: |
            echo "[scw] "$(docker run -it scaleway-cli "scw"  "version" | head -n 1)
            echo "[kubectl] "$(docker run -it scaleway-cli "kubectl"  "version" | head -n 1)
            echo "[python3] "$(docker run -it scaleway-cli "python3"  "--version" | head -n 1)
            echo "[curl] "$(docker run -it scaleway-cli "curl" "--version" | head -n 1)
            echo "[git] "$(docker run -it scaleway-cli "git" "--version" | head -n 1)
            echo "[docker] "$(docker run -it scaleway-cli "docker" "--version" | head -n 1)
            echo "[jq] "$(docker run -it scaleway-cli "jq" "--version" | head -n 1)
            echo "[ytt] "$(docker run -it scaleway-cli "ytt" "--version" | head -n 1)
            echo "[psql] "$(docker run -it scaleway-cli "psql" "--version" | head -n 1)
            echo "[mariadb-client] "$(docker run -it scaleway-cli "mysql" "--version" | head -n 1)

  publish-latest-docker-image:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -t "aegirops/scaleway-cli:latest" -t "aegirops/scaleway-cli:${CIRCLE_TAG}" . --no-cache
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push aegirops/scaleway-cli:latest
            docker push aegirops/scaleway-cli:${CIRCLE_TAG}

workflows:
  build-test:
    jobs:
      - build-docker-image:
          filters:
            branches:
              only:
                - /.*/

  publish:
    jobs:
      - publish-latest-docker-image:
          context: dockerScalewayCli
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/
